repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        exclude: plugins/debugging_helpers.py

  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black/
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        args:
          - --max-line-length=88
          - --select=C,E,F,W,B,B950
          - --ignore=E203,E501,W503
